### ISSUE TITLE
Colab Protocol Fails on Run Prediction Step

### ISSUE THREAD

**Issue by lsalases** [huhlim/alphafold-multistate#4]
Hi, 

I am trying to use AlphaFold-Multistate for the first time on Colab, but I am getting an error on the Run Prediction step. I was wondering if I am doing something wrong?

Here is what I entered in the Input Protein Sequence step:
![Screenshot from 2023-02-09 14-51-58](https://user-images.githubusercontent.com/5659918/217923598-45cc4767-69a6-4b67-adf1-bf5358525972.png)

Then I hitted Runtime -> Run all.

This is the error I got:
![Screenshot from 2023-02-09 14-54-05](https://user-images.githubusercontent.com/5659918/217923755-31d5912a-38c7-4438-9df7-d5378cca2b00.png)

I will appreciate your help or any suggestions you might have on this issue.

Thanks!

**Comment by huhlim** [comment]
Thank you for pointing out the issue. 
I recognized that there were updates in [AlphaFold](https://github.com/deepmind/alphafold) and [ColabFold](https://github.com/sokrypton/ColabFold) recently. Especially, our Colab notebook scripts utilizes the ColabFold interface, and this has been changed a bit in variable names and several input arguments. I have updated our scripts to reflect the changes and tested them. So, please try it again and let me know if you have any further issues.

**Comment by lsalases** [comment]
It works now! Thanks a lot for your help.

**Comment by huhlim** [comment]
No problem! Thank you for confirming that the new script is working well.
