### ISSUE TITLE
Colab Interface Failed on "Run Prediction" Step

### ISSUE THREAD

**Issue by linhaowei1** [huhlim/alphafold-multistate#5]
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/56622542/220279648-dc753a0e-d1ea-46f2-b4ca-2630054ab700.png">
I run the colab interface of alphafold-multistate with the default configurations, but it fails. The reason seems to be that the ColabFold API has been updated. Can you take a look of this? Thanks:)

**Comment by huhlim** [comment]
Thank you for noticing me. I fixed the issue, and our Colab notebook seems to be working now.

**Comment by linhaowei1** [comment]
Nice! Thanks a lot.
