### ISSUE TITLE
Conflicting versions of packages

### ISSUE THREAD

**Issue by ZhunanStevenSun** [huhlim/alphafold-multistate#8]
Hi, I tried to run the Colab version of AlphaFold-multistate, but it failed on 'Install dependencies' step. It seems like there's some packages with conflicting versions that cannot be installed successfully. Could you please fix the issue? Thank you so much!
<img width="1343" alt="AF_MS_issue" src="https://github.com/huhlim/alphafold-multistate/assets/152196992/2072eead-cc5f-4348-abdb-8c4e5edc2ffc">

**Comment by huhlim** [comment]
Thank you for reporting the issue. I resolved the issue.
I'd like to note that the current Colab notebook only works for GPCR modeling as I am migrating databases for kinases from Google Drive to Zenodo.

**Comment by ZhunanStevenSun** [comment]
Great, thank you so much.
For me, there is no worry about the kinase part, as I only want to predict active GPCRs.
By the way, I am wondering if this Colab version has an option to refine the structure (e.g. by using Amber)? But it is totally fine if there's not, I can do it myself.

**Comment by huhlim** [comment]
I may update the notebook to enable the OpenMM-based refinement in the near future.
